set -g @theme_bg '#111111'
set -g @theme_surface '#191919'
set -g @theme_surface_alt '#4c4c57'
set -g @theme_fg '#A1A1AC'
set -g @theme_muted '#616167'
set -g @theme_border '#191919'
set -g @theme_accent '#858599'
set -g @theme_cyan '#6d748c'
