set -g @theme_bg '#141415'
set -g @theme_surface '#1c1c24'
set -g @theme_surface_alt '#252530'
set -g @theme_fg '#cdcdcd'
set -g @theme_muted '#606079'
set -g @theme_border '#1c1c24'
set -g @theme_accent '#bb9dbd'
set -g @theme_cyan '#7e98e8'
