[colors.primary]
# background = "#141415"
foreground = "#cdcdcd"

[colors.cursor]
cursor = "#878787"
text = "#141415"

[colors.normal]
black = "#141415"
red = "#d8647e"
green = "#7fa563"
yellow = "#f3be7c"
blue = "#6e94b2"
magenta = "#bb9dbd"
cyan = "#7e98e8"
white = "#cdcdcd"

[colors.bright]
black = "#606079"
red = "#d8647e"
green = "#7fa563"
yellow = "#f3be7c"
blue = "#90a0b5"
magenta = "#c3c3d5"
cyan = "#7e98e8"
white = "#ffffff"
