set -g @theme_bg '#000000'
set -g @theme_surface '#303030'
set -g @theme_surface_alt '#4E4E4E'
set -g @theme_fg '#C6C6C6'
set -g @theme_muted '#767676'
set -g @theme_border '#303030'
set -g @theme_accent '#a790d5'
set -g @theme_cyan '#4FB8CC'
