set -g status on
set -g status-position bottom
set -g status-interval 1
set -g status-left-length 40
set -g status-right-length 90
set -g status-justify left

set -g mode-style 'fg=#{@theme_bg},bg=#{@theme_accent}'
set -g message-style 'fg=#{@theme_bg},bg=#{@theme_accent}'
set -g message-command-style 'fg=#{@theme_bg},bg=#{@theme_accent}'
set -g @ui_left_separator ''
set -g @ui_middle_separator ' '
set -g @ui_right_separator ''

set -g pane-border-style 'fg=#{@theme_border},bg=default'
set -g pane-active-border-style 'fg=#{@theme_accent},bg=default'
set -g display-panes-active-colour colour33
set -g display-panes-colour colour166
set -g status-style 'fg=#{@theme_fg},bg=default'

set -g status-left '#[fg=#{@theme_accent},bg=default]#{@ui_left_separator}#[fg=#{@theme_bg},bg=#{@theme_accent},bold]  #{@ui_middle_separator}#[fg=#{@theme_fg},bg=#{@theme_surface}]  #S #[fg=#{@theme_surface},bg=default]#{@ui_right_separator} '
set -g status-right '#[fg=#{@theme_accent},bg=default]#{@ui_left_separator}#[fg=#{@theme_bg},bg=#{@theme_accent},bold]  #{@ui_middle_separator}#[fg=#{@theme_fg},bg=#{@theme_surface}]  #{b:pane_current_path} #[fg=#{@theme_surface},bg=default]#{@ui_right_separator} #[fg=#{@theme_surface},bg=default]#{@ui_left_separator}#[fg=#{@theme_fg},bg=#{@theme_surface},bold] %H:%M #[fg=#{@theme_surface},bg=default]#{@ui_right_separator}'

setw -g window-status-separator ' '
setw -g window-status-activity-style 'underscore,fg=#{@theme_accent},bg=default'
setw -g window-status-style 'fg=#{@theme_fg},bg=default'
setw -g window-status-format '#[fg=#{@theme_fg},bg=default,bold] #W #[fg=#{@theme_surface_alt},bg=default]#{@ui_middle_separator}#[fg=#{@theme_bg},bg=#{@theme_surface_alt},bold]  #I #[fg=#{@theme_surface_alt},bg=default]#{@ui_right_separator}'
setw -g window-status-current-style 'fg=#{@theme_fg},bg=default'
setw -g window-status-current-format '#[fg=#{@theme_fg},bg=default,bold] #W#{?window_zoomed_flag, (Z),} #[fg=#{@theme_accent},bg=default]#{@ui_middle_separator}#[fg=#{@theme_bg},bg=#{@theme_accent},bold]  #I #[fg=#{@theme_accent},bg=default]#{@ui_right_separator}'
